##
# Rules for markdownlint.
#
# See https://github.com/DavidAnson/markdownlint
##

default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 100
  # Number of characters for headings
  heading_line_length: 100
  # Number of characters for code blocks
  code_block_line_length: 100
  # Line length requirement disabled for
  code_blocks: false
  tables: false
