micronaut:
  io:
    watch:
      paths: src
      restart: true
  router:
    static-resources:
      swagger:
        enabled: true
        paths: classpath:swagger
        mapping: /**
  server:
    netty:
      access-logger:
        enabled: true
        logger-name: http

nshmp-haz:
  ##
  # The path to the models.
  # To specify the model to use:
  #     java -jar build/libs/nshmp-haz.jar --models=<path/to/models>
  #
  model-path: ${models:libs/nshmp-haz-dep--nshm-hi-2021}
  # model-path: ${models:libs/nshmp-haz-dep--nshm-conus-2018}
