micronaut:
  io:
    watch:
      paths: src
      restart: true
  router:
    static-resources:
      swagger-yml:
        enabled: true
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger:
        enabled: true
        paths: classpath:swagger
        mapping: /**

nshmp-haz:
  ##
  # The path to the models.
  # To specify the model to use:
  #     java -jar build/libs/nshmp-haz-v2.jar --models=<path/to/models>
  model-path: ${models:libs/nshmp-haz-dep--nshm-conus-2018}
