micronaut:
  io:
    watch:
      paths: src
      restart: true
  router:
    static-resources:
      swagger:
        enabled: true
        paths: classpath:swagger
        mapping: /**

nshmp-haz:
  ##
  # The basin service url
  # To specify the url to use:
  #     java -jar build/libs/nshmp-haz.jar --basin-service-url=
  basin-service-url: ${basin-service-url:https://staging-earthquake.usgs.gov/nshmp/ws/data/basin}

  ##
  # The path to the models.
  # To specify the model to use:
  #     java -jar build/libs/nshmp-haz.jar --models=<path/to/models>
  model-path: ${models:libs/nshmp-haz-dep--nshm-conus-2018}
