version: "3.7"

services:
  # Deploy nshmp-haz with HI-2020
  nshmp-haz-hi-2020:
    image: ${REGISTRY}/${IMAGE_NAME}
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 3
      update_config:
        order: start-first
        parallelism: 3
    ports:
      - 8080
    environment:
      RUN_HAZARD: 'false'
      MODEL: HI-2020
      CONTEXT_PATH: hawaii-2020

  # Deploy nshmp-haz with CONUS-2018
  nshmp-haz-conus-2018:
    image: ${REGISTRY}/${IMAGE_NAME}
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 3
      update_config:
        order: start-first
        parallelism: 3
    ports:
      - 8080
    environment:
      RUN_HAZARD: 'false'
      MODEL: CONUS-2018

  # Deploy nshmp-haz with CONUS-2014
  nshmp-haz-conus-2014:
    image: ${REGISTRY}/${IMAGE_NAME}
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 3
      update_config:
        order: start-first
        parallelism: 3
    ports:
      - 8080
    environment:
      RUN_HAZARD: 'false'
      MODEL: CONUS-2014

  # Deploy nshmp-haz with CONUS-2014B
  nshmp-haz-conus-2014b:
    image: ${REGISTRY}/${IMAGE_NAME}
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 3
      update_config:
        order: start-first
        parallelism: 3
    ports:
      - 8080
    environment:
      RUN_HAZARD: 'false'
      MODEL: CONUS-2014B

  # Deploy nshmp-haz with CONUS-2008
  nshmp-haz-conus-2008:
    image: ${REGISTRY}/${IMAGE_NAME}
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 3
      update_config:
        order: start-first
        parallelism: 3
    ports:
      - 8080
    environment:
      RUN_HAZARD: 'false'
      MODEL: CONUS-2008

  # Deploy nshmp-haz with AK-2007
  nshmp-haz-ak-2007:
    image: ${REGISTRY}/${IMAGE_NAME}
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 3
      update_config:
        order: start-first
        parallelism: 3
    ports:
      - 8080
    environment:
      RUN_HAZARD: 'false'
      MODEL: AK-2007
      CONETEXT_PATH: alaska-2007
